export const dummyProfiles = [
  {
    first_name: 'John',
    last_name: 'Doe',
    bio:
      "I'm a zoology student passionate about studying Scottish seabirds and their ecosystems. I have a strong interest in wildlife conservation and am eager to expand my knowledge through interest_fieldswork and research. I'm ...",
    location: 'Glasgow',
    institution: Math.floor(Math.random() * 3) + 1,
    interest_fields: [1, 2],
    interest_activities: [1, 3],
    picture:
      'https://cdn.builder.io/api/v1/image/assets/TEMP/fa0411b9437e4f5c94dc592ae540ca931fa56c1a5bc804ba182079851808fd12?placeholderIfAbsent=true&apiKey=7f28d5e587f84df7a5822226ed5ed8c3',
  },
  {
    first_name: 'Jane',
    last_name: 'Smith',
    bio:
      "I'm a marine biologist specializing in coral reef ecosystems and their preservation. I enjoy diving and conducting underwater research to study the effects of climate change on marine biodiversity.",
    location: 'Edinburgh',
    institution: Math.floor(Math.random() * 3) + 1,
    interest_fields: [2, 3],
    interest_activities: [2],
    picture: 'https://randomuser.me/api/portraits/men/10.jpg',
  },
  {
    first_name: 'Emma',
    last_name: 'Johnson',
    bio:
      "As a botany enthusiast, I study rare and endangered tree species in Scotland. My work focuses on sustainable forestry practices and habitat restoration to conserve native ecosystems.",
    location: 'Glasgow',
    institution: Math.floor(Math.random() * 3) + 1,
    interest_fields: [1, 3],
    interest_activities: [1, 2],
    picture: 'https://randomuser.me/api/portraits/women/20.jpg',
  },
  {
    first_name: 'Oliver',
    last_name: 'Brown',
    bio:
      "I'm a wildlife photographer and interest_fields researcher passionate about documenting bird migration patterns across the UK. I also conduct workshops on wildlife conservation and photography.",
    location: 'Edinburgh',
    institution: Math.floor(Math.random() * 3) + 1,
    interest_fields: [1],
    interest_activities: [3],
    picture: 'https://randomuser.me/api/portraits/men/30.jpg',
  },
  {
    first_name: 'Sophia',
    last_name: 'Williams',
    bio:
      "I'm an ecologist focusing on the study of urban green spaces and their role in enhancing biodiversity. I work with local communities to create and maintain wildlife-friendly gardens.",
    location: 'Glasgow',
    institution: Math.floor(Math.random() * 3) + 1,
    interest_fields: [3],
    interest_activities: [2, 3],
    picture: 'https://randomuser.me/api/portraits/women/40.jpg',
  },
  {
    first_name: 'William',
    last_name: 'Jones',
    bio:
      "As a fisheries scientist, I research sustainable fishing methods and aquatic ecosystem health. My goal is to balance industry needs with environmental conservation.",
    location: 'Edinburgh',
    institution: Math.floor(Math.random() * 3) + 1,
    interest_fields: [2],
    interest_activities: [1, 2],
    picture: 'https://randomuser.me/api/portraits/men/50.jpg',
  },
  {
    first_name: 'Ava',
    last_name: 'Brown',
    bio:
      "I'm a bird enthusiast and conservationist working to protect endangered bird species in Scotland. I love organizing birdwatching tours and educational events for local communities.",
    location: 'Glasgow',
    institution: Math.floor(Math.random() * 3) + 1,
    interest_fields: [1, 2],
    interest_activities: [1],
    picture: 'https://randomuser.me/api/portraits/women/60.jpg',
  },
  {
    first_name: 'Noah',
    last_name: 'Davis',
    bio:
      "I'm an environmental policy advisor specializing in marine ecosystem regulations. My research aims to protect vulnerable fish species and promote eco-friendly fishing practices.",
    location: 'Edinburgh',
    institution: Math.floor(Math.random() * 3) + 1,
    interest_fields: [2, 3],
    interest_activities: [3],
    picture: 'https://randomuser.me/api/portraits/men/70.jpg',
  },
  {
    first_name: 'Mia',
    last_name: 'Miller',
    bio:
      "I study Scotland's native trees, focusing on disease resistance and genetic diversity. My work contributes to reforestation projects and habitat restoration efforts.",
    location: 'Glasgow',
    institution: Math.floor(Math.random() * 3) + 1,
    interest_fields: [1, 3],
    interest_activities: [2],
    picture: 'https://randomuser.me/api/portraits/women/80.jpg',
  },
  {
    first_name: 'James',
    last_name: 'Wilson',
    bio:
      "I'm a conservation biologist with expertise in migratory birds. I collaborate with international teams to track bird movement and develop conservation strategies.",
    location: 'Edinburgh',
    institution: Math.floor(Math.random() * 3) + 1,
    interest_fields: [1],
    interest_activities: [1, 3],
    picture: 'https://randomuser.me/api/portraits/men/90.jpg',
  },
  {
    first_name: 'Liam',
    last_name: 'Moore',
    bio:
      "As a wildlife advocate, I focus on raising public awareness about bird conservation. I organize campaigns and educational programs for schools and communities.",
    location: 'Glasgow',
    institution: Math.floor(Math.random() * 3) + 1,
    interest_fields: [1, 2],
    interest_activities: [2],
    picture: 'https://randomuser.me/api/portraits/women/99.jpg',
  },
  {
    first_name: 'Olivia',
    last_name: 'Taylor',
    bio:
      "I'm a researcher studying the impact of urbanization on fish populations in Scotland's rivers. I aim to develop strategies to mitigate habitat loss.",
    location: 'Edinburgh',
    institution: Math.floor(Math.random() * 3) + 1,
    interest_fields: [2],
    interest_activities: [1, 2],
    picture: 'https://randomuser.me/api/portraits/men/11.jpg',
  },
  {
    first_name: 'Ethan',
    last_name: 'Anderson',
    bio:
      "I specialize in tree ecology and work on projects to preserve ancient woodlands. I enjoy mentoring students and sharing my passion for botany.",
    location: 'Glasgow',
    institution: Math.floor(Math.random() * 3) + 1,
    interest_fields: [3],
    interest_activities: [1],
    picture: 'https://randomuser.me/api/portraits/women/12.jpg',
  },
  {
    first_name: 'Ava',
    last_name: 'Thomas',
    bio:
      "I'm a researcher focused on the role of birds in pollination and seed dispersal. I enjoy interest_fieldswork and collaborating with international research teams.",
    location: 'Edinburgh',
    institution: Math.floor(Math.random() * 3) + 1,
    interest_fields: [1, 3],
    interest_activities: [2, 3],
    picture: 'https://randomuser.me/api/portraits/men/13.jpg',
  },
  {
    first_name: 'Noah',
    last_name: 'Hernandez',
    bio:
      "I study the genetics of native Scottish fish species to better understand their adaptability and resilience to environmental changes.",
    location: 'Glasgow',
    institution: Math.floor(Math.random() * 3) + 1,
    interest_fields: [2],
    interest_activities: [3],
    picture: 'https://randomuser.me/api/portraits/women/14.jpg',
  },
  {
    first_name: 'Mia',
    last_name: 'Young',
    bio:
      "I'm a conservationist focusing on tree planting projects in urban areas. I aim to create sustainable green spaces that enhance biodiversity.",
    location: 'Edinburgh',
    institution: Math.floor(Math.random() * 3) + 1,
    interest_fields: [3],
    interest_activities: [1, 2],
    picture: 'https://randomuser.me/api/portraits/men/99.jpg',
  },
  {
    first_name: 'James',
    last_name: 'King',
    bio:
      "I work as an ornithologist studying the nesting behavior of seabirds. My research helps inform conservation policies for marine ecosystems.",
    location: 'Glasgow',
    institution: Math.floor(Math.random() * 3) + 1,
    interest_fields: [1],
    interest_activities: [2],
    picture: 'https://randomuser.me/api/portraits/women/16.jpg',
  },
  {
    first_name: 'Liam',
    last_name: 'Wright',
    bio:
      "I'm a fisheries manager focusing on sustainable practices in aquaculture. I work to ensure a balance between economic growth and environmental health.",
    location: 'Edinburgh',
    institution: Math.floor(Math.random() * 3) + 1,
    interest_fields: [2, 3],
    interest_activities: [1, 3],
    picture: 'https://randomuser.me/api/portraits/men/17.jpg',
  },
  {
    first_name: 'Olivia',
    last_name: 'Scott',
    bio:
      "I study the ecological impact of tree diseases and work to develop strategies to combat them. I also enjoy teaching workshops on forest ecology.",
    location: 'Glasgow',
    institution: Math.floor(Math.random() * 3) + 1,
    interest_fields: [3],
    interest_activities: [1, 2],
    picture: 'https://randomuser.me/api/portraits/women/18.jpg',
  },
  {
    first_name: 'Ethan',
    last_name: 'Adams',
    bio:
      "I'm a wildlife researcher focusing on the behavior and migration of Scottish seabirds. I work to promote conservation through public engagement.",
    location: 'Edinburgh',
    institution: Math.floor(Math.random() * 3) + 1,
    interest_fields: [1, 2],
    interest_activities: [2, 3],
    picture: 'https://randomuser.me/api/portraits/men/19.jpg',
  },
  {
    first_name: 'Ava',
    last_name: 'Baker',
    bio:
      "I'm a marine conservationist working to protect fish populations in Scotland's coastal waters. I love sharing my knowledge through community outreach programs.",
    location: 'Glasgow',
    institution: Math.floor(Math.random() * 3) + 1,
    interest_fields: [2],
    interest_activities: [1, 3],
    picture: 'https://randomuser.me/api/portraits/women/20.jpg',
  },
];